---

- hosts: all
  become: true
  tasks:
    - name: Add the inventory into /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{% set short_name = item.split('.') %}{{ hostvars[item]['ansible_facts']['eth1']['ipv4']['address'] }} {{item}} {{ short_name[0] }}"
        state: present
      with_items:
        - "{{ groups['all'] }}"
      when: hostvars[item]['ansible_facts']['eth1']['ipv4']['address'] is defined

- hosts: web
  become: true
  vars_files:
    - vars.yaml
  roles:
    - {role: docker, when: CRIO == False and DOCKER == True}
    - {role: crio, when: CRIO == True and DOCKER == False}

# - hosts: db
#   become: true
#   vars_files:
#     - vars.yaml
#   roles:
#     - {role: postgresql}

- hosts: db
  become: true
  vars_files:
    - vars.yaml
  roles:
    - {role: postgresql}
  # tasks:
  #   - name: Wait up to 60 seconds for server to become available after creation
  #     wait_for:
  #       port: 1433
  #       timeout: 60
  #   - name: Create new db
  #     include_role:
  #       name: mssql
  #       tasks_from: new_db
  #   - name: Import database from files directory
  #     include_role:
  #       name: mssql
  #       tasks_from: import_db

# - hosts: git
#   become: true
#   roles:
#     - {role: gitlab}
